### ISSUE TITLE
How to handle timouts when downloading a file

### ISSUE THREAD

**Issue by markpendlebury** [jpdillingham/Soulseek.NET#572] opened 2021-08-21 09:53 UTC
First of all, thank you for your work on this project, it's helped me a lot with a project i'm working on and i'm very grateful!

The problem i have is i'm getting seemingly random timeouts when attempting to download files from users, and i'm not sure how i can handle the timeouts. Ideally i'd like to be able to catch the timeout and try another file from another user.

When i debug my code, sometimes during the download process vscodes debugger hits the "paused" state (i have a play button) i've never seen this before usually i'm able to hit a catch or similar but in this case it just stops, i have to click play for it to actually return the exception.

The exception details are: 

```
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (110): Connection timed out [IPADDRESS]
   at Soulseek.Network.Tcp.Connection.ConnectAsync(Nullable`1 cancellationToken)
   --- End of inner exception stack trace ---
   at Soulseek.Network.Tcp.Connection.ConnectAsync(Nullable`1 cancellationToken)
   at Soulseek.Network.PeerConnectionManager.<>c__DisplayClass37_0.<<GetOrAddMessageConnectionAsync>g__GetConnection|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Soulseek.Network.PeerConnectionManager.RemoveAndDisposeAll()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Soulseek.ConnectionException: Failed to connect to IPADDRESS:2234: Connection timed out [IPADDRESS]:2234
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (110): Connection timed out [IPADDRESS]:2234
3
   at Soulseek.Network.Tcp.Connection.ConnectAsync(Nullable`1 cancellationToken)
   --- End of inner exception stack trace ---
   at Soulseek.Network.Tcp.Connection.ConnectAsync(Nullable`1 cancellationToken)
   at Soulseek.Network.PeerConnectionManager.<>c__DisplayClass37_0.<<GetOrAddMessageConnectionAsync>g__GetConnection|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Soulseek.Network.PeerConnectionManager.RemoveAndDisposeAll()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

I have `connectTimeout` and `inactivityTimeout`  values set in my SoulseekClientOptions and my client.DownloadAsync is like so: 
`await client.DownloadAsync(response.Username, file.Filename, outputStream: fs, startOffset: 0, token: index++, size: file.Size);`

It seems like the client is holding on to the exception somehow and not continuing. Can someone please advise how i can handle this situation/exception correctly? 

Thanks

**Comment by jpdillingham** [comment] 2021-08-21 12:54
The correct way to handle this is to simply wrap the operation in a try/catch and catch `ConnectionException`, which should be retryable.  You can inspect the thrown exception to see if it contains a `TimeoutException`, but because the underlying code tries to negotiate the connection a few different ways this will be unreliable, as there would have been two failures to connect.

Random timeouts, especially when initiating transfers, is pretty common.  You can increase the timeout value and/or add retries to get around it.  My personal plan is to use retries, as increasing connection timeouts will cause delays in other areas.

Regarding the behavior you are seeing in the vscode debugger, I can't really comment as I use Visual Studio almost exclusively for development and always for debugging.

**Comment by markpendlebury** [comment] 2021-08-21 13:49
Thanks for the reply.

I did have the `client.DownloadAsync` method inside a try/catch to catch an `Exception` , i've re-written to catch a `ConnectionException` explicitly but i'm still getting a pause on exception. 

Here's my code: 

```
try
{
    var fs = new FileStream(downloadDirectory + trackName, FileMode.Create, FileAccess.ReadWrite);
    Console.Write($"Downloading {downloadDirectory}{trackName} from {response.Username}...");
    var index = 0;

    var token = new CancellationToken();
    token.ThrowIfCancellationRequested();

    await client.DownloadAsync(response.Username, file.Filename, outputStream: fs, startOffset: 0, token: index++, size: file.Size, cancellationToken: token);
    Console.WriteLine("Done!");
}
catch (ConnectionException conEx)
{
    Console.WriteLine(conEx.ToString());
}                                        
```

And my call stack: 

![image](https://user-images.githubusercontent.com/63231900/130323781-40b479b8-d7fa-40d3-a90e-a6ab201298ba.png)

Yet i'm still unable to catch this exception in order to handle/retry it.

I've removed the timout settings from the options to rely on your defaults (3000ms iirrc?) as i saw as you stated, increasing timeouts simply delays the time it takes to throw the error.

**Comment by jpdillingham** [comment] 2021-08-23 16:01
Can you share a full reproduction, including runtime version and vscode config?  Asking because this is almost certainly some environmental issue, this code has a lot of unit tests around it and I'm not having any issues trapping errors in slskd.

**Comment by markpendlebury** [comment] 2021-08-25 07:17
It seems soulseek is down? At least for me anyway, as soon as it's back up i'll throw a reproduction together and share it for your inspection.

**Comment by jpdillingham** [comment] 2021-10-01 12:05
@markpendlebury I'll close this for now, feel free to re-open if you are still having issues.

**Closed by jpdillingham** 2021-10-01 12:05 UTC
