### ISSUE TITLE
Consider bringing the TargetVersion to netstandard2.0

### ISSUE THREAD

**Issue by ryco117** [jpdillingham/Soulseek.NET#529] opened 2021-04-29 07:41 UTC
The current build requires netstandard2.1when it should be possible to compile the same functionality with only netstandard2.0 and the appropriate Microsoft.Bcl nuget packages.

The reason I raise this issue is that I am likely going to make these exact changes in order to use this library in a Xamarin Forms application and I suspect other people could also be incapable of installing this nuget package because they need to target 2.0.

I suspect these types of issues will be mostly resolved within a year with the unification of net5 and maui replacing XF, but I'm impatient :P If there's a specific reason why this library should target netstandard2.1, I'd also be interested in hearing that.

**Comment by jpdillingham** [comment] 2021-04-29 22:14
I made the branch `netstandard20` as part of #474, and just this morning merged master into it ([diff](https://github.com/jpdillingham/Soulseek.NET/compare/f4352c236d1bfe1326c4eb70ca27a084788e8b23...netstandard20)) if you'd like to build the binaries yourself while I think about this.

The specific reasons for targeting 2.1 over 2.0 are basically what's in the diff above, `IAsyncDisposable`  and ability to use `Memory<T>` with some stream APIs.  I anticipated this being a bigger deal than it ended up being, so I'd be open to targeting 2.0 instead, provided there aren't any measurable performance impacts.  `Connection.ReadInternalAsync` is the hottest path in the library so I'll want to be somewhat certain there's no regression.

**Comment by ryco117** [comment] 2021-05-01 17:21
@jpdillingham Thanks for the detailed response! Ill give your branch a try soon, but 've been working with a local clone that I edited to 2.0 and the library has been working great, nice work.

**Comment by jpdillingham** [comment] 2021-05-01 18:24
@ryco117 I just published prerelease version `2.3.0-pre` to nuget; would you mind testing?  I tried it with a Windows Forms app targeting 4.8 and it works so I can't imagine there'd be a problem, but it would be nice to confirm before making a broad release.

I ended up targeting both 2.0 and 2.1 using preprocessor directives.  I'll probably continue to support 2.0 indefinitely, but I'm not sure about 2.1 since there's a fairly easy upgrade path from .NET Core to 5.

**Comment by ryco117** [comment] 2021-05-01 21:16
It works! Thanks

**Comment by jpdillingham** [comment] 2021-05-02 03:48
Thanks for confirming; I've moved 2.3.0 out of prerelease.

**Closed** 2021-05-02 03:47 UTC
Labels: question, refactor
