### ISSUE TITLE
Download speed is extremely slow

### ISSUE THREAD

**Issue by Dirt-Nasty** [jpdillingham/Soulseek.NET#428] opened 2020-10-31 17:23 UTC
Is there anyway to troubleshoot why my speeds would be extremely slow when running this from the docker container vs running locally?

**Comment by jpdillingham** [comment] 2020-11-01 20:48
Can you elaborate on "running locally"? Are you running the ASP.NET application outside of a container, and it is working as expected?

I'm trying a few different things today and am also noticing that transfers are slow inside of a container.  I'm doing some additional testing to see whether the issue is only with containers.  It is quite possible that my lack of Docker expertise is responsible, but I need to confirm it is a container issue first.

If you could repeat some tests on the same machine (ideally transferring the same files to/from the same remote user) both inside the container and by running the app locally (using [these](https://github.com/jpdillingham/Soulseek.NET#running-without-docker) instructions), it would give me an additional data point.

**Comment by jpdillingham** [comment] 2020-11-02 14:45
The biggest problem is with Linux itself; Windows doesn't seem to care too much what the connection read/write buffers are set to, while Linux is extremely sensitive.  The default buffers were set to 8192, and in doing some benchmarking I found that I could download the same file from the same user at ~150kb/s on Linux vs ~3mb/s on Windows.

I pushed a new build of the image with the buffer sizes set to 64kb and the difference between Linux and Windows is within 10% now.  This is about a 20x (!!) increase in performance on Linux, which naturally includes instances running inside of a container.

I benchmarked both against Soulseek QT and my code is consistently 10-20% slower.  This morning I've spent a few hours rewriting the code that handles message connections to use the new-ish [Pipeline](https://devblogs.microsoft.com/dotnet/system-io-pipelines-high-performance-io-in-net/) library (see commit [here](https://github.com/jpdillingham/Soulseek.NET/commit/e718efc9cfddc5b3491dbea065f1ed4aaddd2c7c)) and there don't seem to be any gains over the present code.  This isn't the same code that is used for file downloads, but it does handle browse results and that's what I've been benchmarking with.  I will probably make another attempt at refactoring the code that reads raw data from the network stream to use pipelines, whether there's an apparent performance gain or not.

Lastly, this library doesn't support obfuscated connections.  I've been skeptical that obfuscation helps in the present day (traffic shaping was definitely a thing 15-20 years ago, no doubt) but this may explain the performance differences.  I won't support obfuscation unless I have concrete evidence that it works; I haven't been able to find any solid documentation around it so to move forward I'd need to spend a lot of time with Wireshark and that is among my least favorite things to do at the moment.

Anyway, give the new image a shot.  I'll create an issue to allow buffer sizes to be changed via environment variables so you can do some experimentation on your own.

**Comment by jpdillingham** [comment] 2020-11-03 20:27
I tested pretty extensively and finally ended up _removing_ the explicit set of the socket buffer size when a connection is initialized.  I have no idea why this behaves this way, but when running on a Linux-like OS, setting the buffer size to anything under 64k reduces performance in a linear fashion with respect to the buffer size (e.g. setting to 32k halves the speed, and so on).  Even setting a buffer size of 512kb offers no improvement over 32k.

By not specifying a buffer size, it seems as though it defers to the OS to manage the buffer, which offers the best performance by far.

Transfer speeds are now _at least_ on par with Soulseek QT, and in limited testing appear to potentially be 5 or 10% faster.

**Closed** 2020-11-03 20:31 UTC
Labels: question
